version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=EdSQLonDocker2022!
      - MSSQL_TCP_PORT=1433
    restart: always
    networks:
      - hishab-network

  hishabnikash:
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}hishabnikash:runtime
    ports:
      - "8080:5000"  # HTTP port
      - "8443:5001"  # HTTPS port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001  # Support both HTTP and HTTPS
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx  # Path to SSL cert
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password1234  # Password for the cert
      - ConnectionStrings__sqlConnection=Server=db;Database=HishabNikash;User Id=sa;Password=EdSQLonDocker2022!;TrustServerCertificate=True;
    build:
      context: .
    volumes:
      - ./certs:/https  # Mount your SSL certificate
    networks:
      - hishab-network

networks:
  hishab-network:
    driver: bridge
